homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude 
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/London
  # Customization file
  customize: !include customize.yaml
  auth_providers:
   - type: homeassistant

#enable the auth component
auth:

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Enable wake-on-lan
wake_on_lan:

# Enable Hive Component
hive:
  username: !secret hive_username
  password: !secret hive_password


frontend: !include frontend.yaml

lovelace:
  mode: yaml

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  base_url: abond.duckdns.org:8123
  ssl_certificate: /home/homeassistant/.homeassistant/ssl/keys/cert.pem
  ssl_key: /home/homeassistant/.homeassistant/ssl/keys/privkey.pem

# Discover some devices automatically
discovery:
  ignore:
    - igd

zwave:

shell_command:
  unlock_landing: /home/homeassistant/.homeassistant/shell/unlock_landing.sh
  lock_landing: /home/homeassistant/.homeassistant/shell/lock_landing.sh
  excelsior_force_shutdown: 'ssh homeassistant@192.168.1.111 sudo shutdown -Ph now'
  turn_off_excelsior: 'ssh homeassistant@192.168.1.111 touch ~/all/shutdown'
  turn_off_defiant: 'ssh homeassistant@defiant.local sudo shutdown -Ph now'
 
# Enables support for tracking state changes over time
history:
  include:
    domains:
      - media_player
      - device_tracker

     
# Add support for weather
weather:
  - platform: darksky
    api_key: !secret darksky_apikey

# View all events in a logbook
logbook:
  exclude:
    entities:
      - device_tracker.andy_phone_bt
      - device_tracker.paula_phone_bt

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Allow diagnosing system problems
system_health:

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say

lightwave: !include lightwave.yaml
group: !include groups.yaml
automation: !include_dir_list automation/
script: !include scripts.yaml
device_tracker: !include device_tracker.yaml
tuya: !include tuya.yaml
switch: !include switches.yaml
sensor: !include sensors.yaml
recorder: !include recorder.yaml
media_player: !include media_players.yaml
