
# Configure a default setup of Home Assistant ie:
#    Automation
#    Home Assistant Cloud
#    Configuration
#    Frontend
#    History
#    Input boolean
#    Input datetime
#    Input number
#    Input select
#    Input text
#    Logbook
#    Map
#    Mobile App Support
#    Person
#    Scene
#    Scripts
#    Simple Service Discovery Protocol (SSDP)
#    Sun
#    System Health
#    Updater
#    Zero-configuration networking (zeroconf)
#    Zone

default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
homeassistant: !include homeassistant.yaml
http: !include http.yaml
automation: !include_dir_list automation/
script: !include scripts.yaml
scene: !include scenes.yaml
lightwave: !include lightwave.yaml
zwave: !include zwave.yaml
frontend: !include frontend.yaml
lovelace: !include lovelace.yaml
sensor: !include sensors.yaml
media_player: !include media_players.yaml
binary_sensor: !include binary_sensors.yaml
switch: !include switches.yaml
alexa: !include alexa.yaml
panel_custom: !include custompanels.yaml
device_tracker: !include device_tracker.yaml
hive: !include hive.yaml
shell_command: !include shell_commands.yaml
recorder: !include recorder.yaml
timer: !include timers.yaml
logbook: !include logbook.yaml
logger: !include logger.yaml
# Required for Amazon Echo Integration
api:
