
# Configure a default setup of Home Assistant ie:
# Assist pipeline (assist_pipeline)
# Backup (backup)
# Bluetooth (bluetooth)
# Configuration (config)
# Conversation (conversation)
# DHCP discovery (dhcp)
# Energy (energy)
# History (history)
# Home Assistant Alerts (homeassistant_alerts)
# Home Assistant Cloud (cloud)
# Image upload (image_upload)
# Logbook (logbook)
# Map (map)
# Media source (media_source)
# Mobile app support (mobile_app)
# My Home Assistant (my)
# Simple Service Discovery Protocol (SSDP) (ssdp)
# Stream (stream)
# Sun (sun)
# USB (usb)
# Webhooks (webhook)
# Zero-configuration networking (zeroconf) (zeroconf)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
homeassistant: !include homeassistant.yaml
http: !include http.yaml
automation: !include_dir_list automation/
script: !include scripts.yaml
scene: !include scenes.yaml
lightwave: !include lightwave.yaml
frontend: !include frontend.yaml
lovelace: !include lovelace.yaml
sensor: !include sensors.yaml
media_player: !include media_players.yaml
binary_sensor: !include binary_sensors.yaml
switch: !include switches.yaml
alexa: !include alexa.yaml
device_tracker: !include device_tracker.yaml
shell_command: !include shell_commands.yaml
recorder: !include recorder.yaml
timer: !include timers.yaml
logbook: !include logbook.yaml
logger: !include logger.yaml
notify: !include notify.yaml
mqtt: !include mqtt.yaml
panel_iframe: !include tasmota.yaml
#command_line: !include command_line.yaml

# Check the size of the log file
command_line:
  - sensor:
      name: log_file_size
      command: "du -k /config/home-assistant.log | cut -f1"
      unit_of_measurement: 'KB'
      value_template: '{{ value }}'



#light: !include light.yaml

# Required for Amazon Echo Integration
api:


