alias: Bass Amp OFF
initial_state: false
trigger:
  platform: state  
  entity_id: binary_sensor.lounge_amp
  to: "off"
  for: '00:02:00'
action:
  - service: switch.turn_off
    entity_id: switch.bass_amp
