alias: Bass Amp ON
initial_state: false
trigger:
  platform: state  
  entity_id: sensor.bass_amp
  to: "on" 
action:
  - service: switch.turn_on
    entity_id: switch.bass_amp
  - delay: '00:00:10'
  - service: switch.turn_on
    entity_id: switch.bass_amp