alias: Computers Off
id: computers_off
trigger:
  - platform: state
    entity_id: group.computers
    to: "off"
    for: "00:10:00"
action:
  - action: switch.turn_off
    target:
      entity_id: switch.pc_speaker
