alias: Defiant Switched Off
initial_state: false
trigger:
  platform: state  
  entity_id: device_tracker.defiant
  from: "home"
  to: "not_home" 
action:
  - service: switch.turn_off
    entity_id: switch.defiant
