alias: Defiant Switched Off
initial_state: false
trigger:
  platform: state  
  entity_id: binary_sensor.defiant
  from: "on"
  to: "off" 
  for: '00:05:00'
action:
  - service: switch.turn_off
    entity_id: switch.defiant
