alias: Disable Landing Lights
trigger:
  platform: state
  entity_id: sensor.dark
  to: 'no'
action:
  - service: shell_command.lock_landing
  - delay: '00:00:15'
  - service: shell_command.lock_landing

