# Empty Log file if size > 4 MB
alias: 'Empty Log File'
id: empty_log_file
trigger:
  - platform: template
    value_template: "{{ states.sensor.log_file_size.state | int > 4096 }}"
action:
  - service: shell_command.clear_log
