id: enterprise_statechange
alias: Enterprise State Change
trigger:
  - platform: mqtt
    topic: "enterprise/status"
action:
  - action: notify.persistent_notification
    data:
      message: "{{ trigger.payload }}"
