alias: Excelsior Switched Off
initial_state: false
trigger:
  platform: state  
  entity_id: binary_sensor.excelsior
  from: "on"
  to: "off" 
  for: '00:05:00'
action:
#  - service: switch.turn_off
#    entity_id: switch.excelsior
#  - delay: '00:00:15'
#  - service: switch.turn_off
#    entity_id: switch.excelsior
  - service: homeassistant.turn_off
    entity_id: group.excelsior_usb_drives
  - delay: '00:00:30'
  - service: homeassistant.turn_off
    entity_id: group.excelsior_usb_drives
