id: excelsior_statechange
alias: Excelsior State Change
trigger:
  - platform: mqtt
    topic: "excelsior/status"
action:
  - action: notify.persistent_notification
    data:
      message: "{{ trigger.payload }}"
