alias: Excelsior Switched Off
initial_state: false
trigger:
  platform: state  
  entity_id: device_tracker.excelsior
  from: "home"
  to: "not_home" 
  for: '00:05:00'
action:
  - service: switch.turn_off
    entity_id: switch.excelsior
  - delay: '00:00:05'
  - service: switch.turn_off
    entity_id: switch.excelsior_usbs
  - delay: '00:00:05'
  - service: homeassistant.turn_off
    entity_id: group.excelsior_usb_drives
