alias: Excelsior Auto Switch On
id: excelsior_auto_on
trigger:
  - platform: time
    # Military time format. This trigger will fire at 4:00 AM
    at: '04:00:00'
action:
  - action: switch.turn_on
    target:
      entity_id: switch.excelsior_wol
