alias: Turn off hall light (pir)
id: Turn_off_hall_light_(pir)
#BELT AND BRACES SWITCH OFF
trigger:
  platform: state
  entity_id: binary_sensor.multisensor_6_motion_detection
  to: "off"
  for:
    seconds: 600
action:
  - service: script.hall_light_off


