
alias: Turn on hall light on movement
trigger:
  platform: state
  entity_id: binary_sensor.pir_hall
  to: "on"
#  for: 3
#condition:
#  - condition: state
#    entity_id: sun.sun
#    state: "below_horizon"
action:
  - service: switch.turn_on
    entity_id: switch.hall_light
  - service: switch.turn_on
    entity_id: switch.pc_light


