alias: Turn on hall light on pir detect
id: hall_light_on.yaml
trigger:
  platform: state
  entity_id: binary_sensor.multisensor_6_motion_detection
  to: "on"
mode: restart
condition: 
  condition: state 
  entity_id: sensor.dark
  state: 'yes'
action:
  - service: script.hall_light_on


