
alias: Turn on hall light on radar detect
trigger:
  platform: state
  entity_id: binary_sensor.radar_hall
  to: "on"
#  for: 3
condition:
  - condition: sun
    after: sunset
    after_offset: "-01:00:00"
  - condition: state
    entity_id: binary_sensor.pir_hall
    state: "on"
  - condition: state
    entity_id: switch.hall_light
    state: "off"
action:
  - service: switch.turn_on
    entity_id: switch.hall_light
#  - service: switch.turn_on
#    entity_id: switch.pc_light


