alias: Turn on hall light on pir detect
trigger:
  platform: state
  entity_id: binary_sensor.aeon_labs_zw100_multisensor_6_sensor
  to: "on"
condition: 
  condition: state 
  entity_id: sensor.dark
  state: 'yes'
action:
  - service: switch.turn_on
    entity_id: switch.hall_light


