
alias: Turn off hall light (pir)
#BELT AND BRACES SWITCH OFF
trigger:
  platform: event
  event_type: timer.finished
  event_data:
    entity_id: timer.hall_light_off
#  entity_id: binary_sensor.aeon_labs_zw100_multisensor_6_sensor
#  to: "off"
#  for:
#    minutes: 3
#condition:
#  - condition: state
#    entity_id: switch.hall_light
#    state: "on"
action:
  - service: switch.turn_off
    entity_id: switch.hall_light
  - service: switch.turn_off
    entity_id: switch.porch_light
  - delay: '00:00:10'
  - service: switch.turn_off
    entity_id: switch.hall_light
  - service: switch.turn_off
    entity_id: switch.porch_light


