alias: Hall light motion control
id: hall_light_motion_control
mode: restart

trigger:
  - platform: state
    entity_id: binary_sensor.multisensor_6_motion_detection
    to: "on"

condition:
  - condition: state
    entity_id: sensor.dark
    state: 'yes'

action:
  - action: script.hall_light_on

  - wait_for_trigger:
      - platform: state
        entity_id: binary_sensor.multisensor_6_motion_detection
        to: "off"
        for:
          minutes: 1

  - action: script.hall_light_off
  - action: script.porch_light_off
