alias: Turn Kodi Lounge OFF
trigger:
  platform: state  
  entity_id: remote.lounge
condition:
  condition: template
  value_template: '{{ trigger.to_state.attributes.current_activity != "Kodi" and trigger.to_state.state != "unavailable" }}'
action:
  service: kodi.call_method
  data:
    entity_id: media_player.lounge_kodi
    method: System.Shutdown
