alias: Turn Kodi Lounge ON
trigger:
  platform: state  
  entity_id: remote.harmony_hub
condition:
  condition: template
  value_template: '{{ trigger.to_state.attributes.current_activity == "Kodi" }}'
action:
  service: switch.turn_on
  entity_id: switch.kodi_lounge
