alias: Turn on landing light on pir detect
id: landing_light_on
mode: restart

trigger:
  - platform: state
    entity_id: binary_sensor.pir_motion_temperature_light_sensor_motion_detection
    to: "on"

condition:
  - condition: state
    entity_id: sensor.dark
    state: 'yes'

action:
  - action: script.landing_light_on

  - wait_for_trigger:
      - platform: state
        entity_id: binary_sensor.pir_motion_temperature_light_sensor_motion_detection
        to: "off"
        for:
          minutes: 1

  - action: script.landing_light_off
