id: lexington_fault
alias: Lexington Fault Report
trigger:
  - platform: mqtt
    topic: "lexington/fault"
action:
  - action: notify.persistent_notification
    data:
      message: "{{ trigger.payload }}"
