id: lexington_statechange
alias: Lexington State Change
trigger:
  - platform: mqtt
    topic: "lexington/status"
action:
  - service: notify.persistent_notification
    data:
      message: '{{ trigger.payload }}'
