alias: Lounge Lights
id: lounge_lights
trigger:
  platform: state
  entity_id: sensor.dark
  to: 'yes'
condition:
  condition: state
  entity_id: sensor.lounge_occupied
  state: "yes"
action:
  - service: script.turn_on_lounge_lights
