alias: Lounge Lights
trigger:
  platform: sun
  event: sunset 
condition:
  condition: or
  conditions:
    - condition: state
      entity_id: group.tracker_paula
      state: home
    - condition: state
      entity_id: group.tracker_andy
      state: home
action:
  service: homeassistant.turn_on
  entity_id: group.lounge_lights

