alias: Lounge Kodi USB OFF
initial_state: false
trigger:
  platform: state  
  entity_id: binary_sensor.lounge_kodi
  from: "on"
  to: "off" 
  for: '00:02:00'
action:
  - service: switch.turn_off
    entity_id: switch.lounge_kodi_usb
