alias: Lounge Lights
trigger:
  platform: sun
  event: sunset 
condition:
  - condition: state
    entity_id: group.residents
    state: home
  - condition: state
    entity_id: device_tracker.tv_lounge
    state: home
action:
  - service: homeassistant.turn_on
    entity_id: switch.picture_light
  - delay: 2
  - service: homeassistant.turn_on
    entity_id: switch.standing_light
  - delay: 2
  - service: homeassistant.turn_on
    entity_id: switch.unit_lights
