alias: Lounge Lights
trigger:
  platform: state
  entity_id: sensor.dark
  to: "yes"
condition:
  condition: state
  entity_id: device_tracker.tv_lounge
  state: home
action:
  - service: homeassistant.turn_on
    entity_id: switch.picture_light
  - delay: 2
  - service: homeassistant.turn_on
    entity_id: switch.standing_light
  - delay: 2
  - service: homeassistant.turn_on
    entity_id: switch.unit_lights
