alias: Lounge Lights
trigger:
  platform: state
  entity_id: sensor.dark
  to: "yes"
condition:
  condition: state
  entity_id: device_tracker.tv_lounge
  state: home
action:
  - service: script.turn_on_lounge_lights
