alias: Lounge Lights 2
trigger:
  platform: state  
  entity_id: binary_sensor.lounge_tv
  to: "on" 
condition:
  condition: state
  entity_id: sensor.dark
  state: 'yes'
  for: '00:02:00'
action:
  - service: script.turn_on_lounge_lights
