alias: Lounge Lights
trigger:
  platform: state
  entity_id: sensor.dark
  to: 'yes'
  for: '00:02:00'
condition:
  condition: state
  entity_id: binary_sensor.lounge_tv
  state: "on"
action:
  - service: script.turn_on_lounge_lights
