alias: Lounge Kodi USB ON
initial_state: false
trigger:
  platform: state  
  entity_id: binary_sensor.lounge_kodi
  to: "on" 
action:
  - service: switch.turn_on
    entity_id: switch.lounge_kodi_usb
