alias: Lounge Lights 2
trigger:
  platform: state  
  entity_id: binary_sensor.lounge_tv
  to: "on" 
condition:
  - condition: state
    entity_id: sensor.dark
    state: 'yes'
    for: '00:02:00'
  - condition: template
    value_template: '{{ as_timestamp(now()) - as_timestamp(states.automation.lounge_lights_2.attributes.last_triggered) | int > 43200 }}'
action:

action:
  - service: script.turn_on_lounge_lights