alias: Mancave Kodi USB OFF
initial_state: false
trigger:
  platform: state  
  entity_id: binary_sensor.mc_kodi
  from: "on"
  to: "off"
  for: '00:02:00' 
action:
  - service: switch.turn_off
    entity_id: switch.05200304bcddc2e0fa9b_2
  - service: switch.turn_off
    entity_id: switch.kodi_usb_2
