alias: Mancave Kodi USB ON
initial_state: false
trigger:
  platform: state  
  entity_id: device_tracker.wetek_hub
  to: "home" 
action:
  - service: switch.turn_on
    entity_id: switch.05200304bcddc2e0fa9b_2
  - service: switch.turn_on
    entity_id: switch.kodi_usb_2
