alias: Mancave Light OFF
trigger:
  platform: state  
  entity_id: sensor.mancave_occupied
  to: "no" 
action:
  - delay: '00:00:45'
  - service: switch.turn_off
    entity_id: switch.05200304bcddc2e0fa9b_1