alias: Mancave Light On 2
id: mc_light_on2.yaml
trigger:
  platform: state
  entity_id: sensor.dark
  to: 'yes'
condition:
  - condition: state
    entity_id: sensor.mancave_occupied
    state: "yes"
action:
  service: homeassistant.turn_on
  entity_id: switch.mancave_light

