alias: Mancave light ON
initial_state: false
trigger:
  platform: state  
  entity_id: device_tracker.tv_mancave
  to: "home" 
condition:
  condition: state
  entity_id: sensor.dark
  state: "yes"
action:
  - service: switch.turn_on
    entity_id: switch.05200304bcddc2e0fa9b_1
