
alias: Mancave light ON
initial_state: false
trigger:
  platform: state  
  entity_id: sensor.mancave_occupied
  to: "yes"
condition:
  condition: state
  entity_id: sensor.dark
  state: 'yes'
  for: '00:01:00'
action:
  - service: switch.turn_on
    entity_id: switch.05200304bcddc2e0fa9b_1
