alias: "Mancave Light ON"
id: mc_light_on
mode: single

trigger:
  # Trigger 1: You walk into the room
  - platform: state
    entity_id: sensor.mancave_occupied
    to: "yes"
    id: "mc_occupied"

  # Trigger 2: It gets dark outside while you're already inside
  - platform: state
    entity_id: sensor.dark
    to: "yes"
    id: "it_got_dark"

condition:
  # Both conditions MUST be true for the light to turn on
  - condition: state
    entity_id: sensor.mancave_occupied
    state: "yes"
  - condition: state
    entity_id: sensor.dark
    state: "yes"

action:
  - action: switch.turn_on
    target:
      entity_id: switch.mancave_light
