alias: Mancave Light OFF
id: mc_light_off
trigger:
  - platform: state
    entity_id: sensor.mancave_occupied
    to: "no"
    for: "00:00:45"
action:
  - action: switch.turn_off
    target:
      entity_id: switch.mancave_light
