
alias: Mancave Light On 2
initial_state: false
trigger:
  platform: state
  entity_id: sensor.dark
  to: 'yes'
  for: '00:01:00'
condition:
  - condition: state
    entity_id: sensor.mancave_occupied
    state: "yes"
action:
  service: homeassistant.turn_on
  entity_id: switch.05200304bcddc2e0fa9b_1

