alias: NAS Drive OFF
initial_state: false
trigger:
  platform: state  
  entity_id: group.computers
  from: "on"
  to: "off"
  for: "00:05:00"
action:
  - service: switch.turn_off
    entity_id: switch.defiant_wol
  - delay: '00:00:30'
  - service: switch.turn_off
    entity_id: switch.defiant_wol

