alias: Start Timer when paula phone wifi not detected
trigger:
  platform: state
  entity_id: binary_sensor.paula_phone_wifi
  to: "off"
action:
  - service: timer.start
    entity_id: timer.paula_away