alias: printer cyan
trigger:
  platform: event
  event_type: state_changed
  event_data:
    entity_id: sensor.hp_color_laser_150nw_cyan_toner_s_n_crum_190702a26c0
condition:
  - condition: template
    value_template: "{{ not is_state('sensor.hp_color_laser_150nw_cyan_toner_s_n_crum_190702a26c0', 'unavailable') }}"
action:
  service: mqtt.publish
  data:
    topic: "printer/cyan"
    payload_template: "{{ states('sensor.hp_color_laser_150nw_cyan_toner_s_n_crum_190702a26c0') }}"
    retain: true