alias: printer magenta
trigger:
  platform: event
  event_type: state_changed
  event_data:
    entity_id: sensor.hp_color_laser_150nw_magenta_toner_s_n_crum_190702a0503
condition:
  - condition: template
    value_template: "{{ not is_state('sensor.hp_color_laser_150nw_magenta_toner_s_n_crum_190702a0503', 'unavailable') }}"
action:
  service: mqtt.publish
  data:
    topic: "printer/magenta"
    payload_template: "{{ states('sensor.hp_color_laser_150nw_magenta_toner_s_n_crum_190702a0503') }}"
    retain: true