alias: "Printer Yellow"
id: printer_yellow
trigger:
  - platform: state
    entity_id: sensor.hp_color_laser_150nw_yellow_toner_s_n_crum_240426a5e0b
condition:
  - condition: template
    value_template: "{{ not is_state('sensor.hp_color_laser_150nw_yellow_toner_s_n_crum_240426a5e0b', 'unavailable') }}"
action:
  - action: mqtt.publish
    data:
      topic: "printer/yellow"
      payload: "{{ states('sensor.hp_color_laser_150nw_yellow_toner_s_n_crum_240426a5e0b') }}"
      retain: true
