alias: "Printer Magenta"
id: printer_magenta
trigger:
  - platform: state
    entity_id: sensor.hp_color_laser_150nw_magenta_toner_s_n_crum_240426a4a9b
condition:
  - condition: template
    value_template: "{{ not is_state('sensor.hp_color_laser_150nw_magenta_toner_s_n_crum_240426a4a9b', 'unavailable') }}"
action:
  - action: mqtt.publish
    data:
      topic: "printer/magenta"
      payload: "{{ states('sensor.hp_color_laser_150nw_magenta_toner_s_n_crum_240426a4a9b') }}"
      retain: true
