
alias: Radio On
initial_state: false
trigger:
  platform: state
  entity_id: binary_sensor.aeotec_zw100_multisensor_6_sensor
  to: "on"
condition:
  - condition: time
    after: 07:00:00
    before: 07:59:59
  - condition: state
    entity_id: 'group.residents'
    state: 'home'
  - condition: template
    value_template: '{{ as_timestamp(now()) - as_timestamp(states.automation.radio_on.attributes.last_triggered) | int > 3660 }}'
action:
  - data:
      entity_id: media_player.roberts_stream_93i_002261c731a0
    entity_id: media_player.roberts_stream_93i_002261c731a0
    service: media_player.turn_on
  - data:
      entity_id: media_player.roberts_stream_93i_002261c731a0
      source: DAB
    service: media_player.select_source
