
alias: Radio On
initial_state: false
trigger:
  entity_id: binary_sensor.pir_hall
  platform: state
  to: 'on'
condition:
  - condition: time
    after: 07:00:00
    before: 07:59:59
  - condition: state
    entity_id: 'group.residents'
    state: 'home'
action:
  - data:
      entity_id: media_player.roberts_stream_93i_002261c731a0
    entity_id: media_player.roberts_stream_93i_002261c731a0
    service: media_player.turn_on
  - data:
      entity_id: media_player.roberts_stream_93i_002261c731a0
      source: Internet radio
    service: media_player.select_source
