alias: Radio On M-F
id: radio_on_m-f
trigger:
  platform: state
  entity_id: binary_sensor.multisensor_6_motion_detection
  to: "on"
condition:
  - condition: time
    after: 07:00:00
    before: 08:59:59
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  - condition: template
    value_template:  >-
      {% if states.automation.radio_on_m_f.attributes.last_triggered %}
        {{ (as_timestamp(now()) - as_timestamp(states.automation.radio_on_m_f.attributes.last_triggered)) > 7260 }}
      {% else %}
        true
      {% endif %}
action:
  - service: switch.toggle
    target:
      entity_id: switch.kitchen_radio_aux_toggle
  - delay: '00:00:10'
  - service: media_player.volume_set
    target:
      entity_id: media_player.jl_tenor
    data:
      volume_level: 0.5

