
alias: Radio On
initial_state: false
trigger:
  platform: state
  entity_id: binary_sensor.multisensor_6_home_security_motion_detection
  to: "on"
condition:
  - condition: time
    after: 07:00:00
    before: 08:59:59
  - condition: state
    entity_id: 'sensor.any_home'
    state: 'yes'
  - condition: template
    value_template: '{{ as_timestamp(now()) - as_timestamp(states.automation.radio_on.attributes.last_triggered) | int > 7260 }}'
action:
  - data:
      entity_id: media_player.jl_tenor
    entity_id: media_player.jl_tenor
    service: media_player.turn_on
  - data:
      entity_id: media_player.jl_tenor
      volume_level: 0.4
    entity_id: media_player.jl_tenor
    service: media_player.volume_set
  - data:
      entity_id: media_player.jl_tenor
#      source: DAB
      source: 'DAB'
    service: media_player.select_source
