
alias: Radio On
initial_state: false
trigger:
  platform: state
  entity_id: binary_sensor.hall_sensor
  to: "on"
condition:
  - condition: time
    after: 07:00:00
    before: 07:59:59
  - condition: state
    entity_id: 'group.residents'
    state: 'home'
  - condition: template
    value_template: '{{ as_timestamp(now()) - as_timestamp(states.automation.radio_on.attributes.last_triggered) | int > 3660 }}'
action:
  - data:
      entity_id: media_player.roberts_radio
    entity_id: media_player.roberts_radio
    service: media_player.turn_on
  - data:
      entity_id: media_player.roberts_radio
      source: DAB
    service: media_player.select_source
