id: saratoga_fault
alias: Saratoga Fault Report
trigger:
  - platform: mqtt
    topic: "saratoga/fault"
action:
  - service: notify.persistent_notification
    data:
      message: '{{ trigger.payload }}'
