alias: Saratoga off at midnight
id: saratoga_off_at_midnight
trigger:
  - platform: time
    at: "00:00:00"
condition:
  - condition: state
    entity_id: binary_sensor.plex_server
    state: "on"
action:
  - action: script.plex_off
