alias: Update Available Notification
trigger:
  platform: state
  entity_id: binary_sensor.updater
  from: 'off'
  to: 'on'
action:
  - service: notify.notify
    data_template:
      message: "Home Assistant {{ state_attr('binary_sensor.updater', 'newest_version') }} is available."
  - delay: '00:00:01'    
  - service: notify.google
    data:
      title: 'Home Assistant: New Version Available'
      message: "Home Assistant {{ state_attr('binary_sensor.updater', 'newest_version') }} is available."