alias: USB Drives OFF
initial_state: false
trigger:
  platform: state  
  entity_id: device_tracker.andy_ubuntu
  from: "home"
  to: "not_home"
action:
  - delay: 30
  - service: homeassistant.turn_off
    entity_id: group.pc_usb_drives

