alias: USB Drives OFF
initial_state: false
trigger:
  platform: state  
  entity_id: binary_sensor.enterprise
  from: "on"
  to: "off"
action:
  - delay: 30
  - service: homeassistant.turn_off
    entity_id: group.main_pc_usb_drives
  - delay: 30
  - service: homeassistant.turn_off
    entity_id: group.main_pc_usb_drives

