alias: "Weekly PC Update"
id: weekly_pc_update
trigger:
  - platform: time
    at: "02:00:00"
condition:
  - condition: time
    weekday:
      - sun
action:
  - action: script.plex_on
  - delay: "00:15:00"
  - action: script.lexington_on
  - delay: "00:15:00"
  - action: script.plex_off
  - delay: "00:15:00"
  - action: script.lexington_off

mode: single
