alias: Welcome Home 2
initial_state: false
trigger:
  platform: state
  entity_id: binary_sensor.shenzhen_neo_electronics_co_ltd_battery_powered_pir_sensor_v2_sensor
  to: "on"
condition:
  condition: and
  conditions: 
    - condition: state 
      entity_id: sensor.dark
      state: 'yes'
    - condition: or
      conditions:
        - condition: state
          entity_id: sensor.all_home
          state: 'no'
        - condition: state
          entity_id: timer.all_home
          state: 'active'
action:
  - service: switch.turn_on
    entity_id: switch.porch_light
  - delay: '00:00:02'
  - service: switch.turn_on
    entity_id: switch.porch_light
  - delay: '00:00:02'
  - service: switch.turn_on
    entity_id: switch.hall_light
  - delay: '00:00:02'
  - service: switch.turn_on
    entity_id: switch.hall_light
  - delay: '00:02:00'
  - service: switch.turn_off
    entity_id: switch.porch_light
  - service: switch.turn_off
    entity_id: switch.hall_light
  - delay: '00:00:10'
  - service: switch.turn_off
    entity_id: switch.porch_light
  - service: switch.turn_off
    entity_id: switch.hall_light
  - delay: '00:00:10'
  - service: switch.turn_off
    entity_id: switch.porch_light
  - service: switch.turn_off
    entity_id: switch.hall_light

