id: welcome_home
alias: Welcome Home 2
initial_state: false
trigger:
  platform: state
  entity_id: binary_sensor.pir_motion_sensor_3_home_security_motion_detection
  to: "on"
condition:
  condition: and
  conditions:
    - condition: time
      before: '23:59:59'
    - condition: state
      entity_id: sensor.dark
      state: 'yes'
action:
  - service: switch.turn_on
    entity_id: switch.porch_light
  - service: script.hall_light_on
  - delay: '00:00:01'
  - service: switch.turn_on
    entity_id: switch.porch_light
  - service: script.hall_light_on
  - service: timer.start
    entity_id: timer.hall_light_off
