alias: Welcome Home 2
initial_state: false
trigger:
  platform: state
  entity_id: binary_sensor.shenzhen_neo_electronics_co_ltd_battery_powered_pir_sensor_v2_sensor
  to: "on"
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: sensor.all_home
      state: 'no'
    - condition: state
      entity_id: sensor.dark
      state: 'yes'
action:
  - service: switch.turn_on
    entity_id: switch.porch_light
  - service: script.hall_light_on
  - delay: '00:00:01'
  - service: switch.turn_on
    entity_id: switch.porch_light
  - service: script.hall_light_on
  - service: timer.start
    entity_id: timer.hall_light_off

