alias: Welcome Home 2
initial_state: false
trigger:
  platform: state
  entity_id: binary_sensor.porch_sensor
  to: "on"
condition:
  condition: state
  entity_id: sun.sun
  state: "below_horizon"
action:
  - service: switch.turn_on
    entity_id: switch.porch_light
  - delay: '00:00:02'
  - service: switch.turn_on
    entity_id: switch.porch_light
  - delay: '00:00:02'
  - service: switch.turn_on
    entity_id: switch.hall_light
  - delay: '00:00:02'
  - service: switch.turn_on
    entity_id: switch.hall_light
  - delay: '00:02:00'
  - service: switch.turn_off
    entity_id: switch.porch_light
  - service: switch.turn_off
    entity_id: switch.hall_light
  - delay: '00:00:10'
  - service: switch.turn_off
    entity_id: switch.porch_light
  - service: switch.turn_off
    entity_id: switch.hall_light
  - delay: '00:00:10'
  - service: switch.turn_off
    entity_id: switch.porch_light
  - service: switch.turn_off
    entity_id: switch.hall_light

