id: welcome_home
alias: Welcome Home 2
trigger:
  platform: state
  entity_id: binary_sensor.porch_sensor_motion_detection
  to: "on"
condition:
  condition: and
  conditions:
    - condition: time
      before: '23:59:59'
    - condition: state
      entity_id: sensor.dark
      state: 'yes'
action:
  - service: script.porch_light_on
