alias: Welcome Home
trigger:
  platform: state  
  entity_id: group.tracker_andy, group.tracker_paula
  from: "not_home"
  to: "home"
condition:
  condition: state
  entity_id: sun.sun
  state: "below_horizon"
action:
  - service: switch.turn_on
    entity_id: switch.porch_light
  - delay: '00:05:00'
  - service: switch.turn_off
    entity_id: switch.porch_light


