alias: Porch light motion control
id: porch_light_motion_control
mode: restart

trigger:
  - platform: state
    entity_id: binary_sensor.porch_sensor_motion_detection
    to: "on"

condition:
  - condition: state
    entity_id: sensor.dark
    state: 'yes'

action:
  - action: script.porch_light_on

  - delay: "00:05:00"

  - action: script.porch_light_off
  - action: script.hall_light_off
